name: MLOps Pipeline

# Trigger workflow on any push to the kernelridge branch
on:
  push:
    branches:
      - "kernelridge"

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Decision Tree training script
      - name: Run DecisionTreeRegressor training
        run: |
          echo "Running DecisionTreeRegressor..."
          python train.py

      # Step 5: Run Kernel Ridge training script
      - name: Run KernelRidge training
        run: |
          echo "Running KernelRidge..."
          python train2.py
